### ISSUE TITLE
Texture2D should support premultiply alpha

### ISSUE THREAD

**Issue by minggo** [minggo/new-renderer#48]
Image should not premultiply alpha by default, should keep the data as it is. Let Texture2D do it according the property `isPremultiplyAlpha`.

**Comment by dumganhar** [comment]
Could refer to https://github.com/dumganhar/webkit/blob/master/Source/WebCore/platform/graphics/FormatConverter.cpp#L618

**Comment by dumganhar** [comment]
fixed at https://github.com/minggo/new-renderer/pull/56
